---
title: "Economic Analysis"
author: "Ishan Bhatt"
date: "11/1/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)

earnings = read_csv("raw-data/employee_earnings_11_1.csv") %>%
  clean_names()
field_contact = read_csv("raw-data/field_contact_rms_10_28.csv") %>%
  clean_names()
property_values = read_csv("raw-data/property_values_11_1.csv") %>%
  clean_names()

property_values$zipcode <- paste0("0", property_values$zipcode)
property_values$zipcode <- property_values$zipcode %>% str_remove(pattern = "-0000")
field_contact$zip <- field_contact$zip %>% str_remove(pattern = "-0000")

```

```{r scraping}

# Boston population data scraping.

library(rvest)

scrape_boston <- function(link) {
  
  x <- read_html(link) %>%
    html_nodes("table")
  
  x[[13]] %>%
   html_table(fill = TRUE) %>%
   row_to_names(1) %>%
   clean_names() %>%
   select(-number, -city, -national_rank)
  
}

pop_1 <- scrape_boston("http://zipatlas.com/us/ma/zip-code-comparison/population-density.htm")
pop_2 <- scrape_boston("http://zipatlas.com/us/ma/zip-code-comparison/population-density.2.htm")
pop_3 <- scrape_boston("http://zipatlas.com/us/ma/zip-code-comparison/population-density.3.htm")
pop_4 <- scrape_boston("http://zipatlas.com/us/ma/zip-code-comparison/population-density.4.htm")
pop_5 <- scrape_boston("http://zipatlas.com/us/ma/zip-code-comparison/population-density.5.htm")


pop <- pop_1 %>%
  rbind(pop_2) %>%
  rbind(pop_3) %>%
  rbind(pop_4) %>%
  rbind(pop_5) %>%
  as.data.frame()

pop$population <- as.numeric(gsub(",","",pop$population))
pop$people_sq_mile<- as.numeric(gsub(",","",pop$people_sq_mile))

rownames(pop) <- 1:nrow(pop)

```

```{r tidying}
# Field contact data modification.

field_tidy <- field_contact %>%
  group_by(zip, basis) %>%
  summarize(count = n(), .groups = "drop") 

field_tidy$count <- as.numeric(field_tidy$count)
  
field_tidy <- field_tidy %>%
  group_by(zip) %>%
  mutate(total = sum(count)) %>%
  ungroup() %>%
  pivot_wider(id_cols = c("zip", "total"), names_from = basis, values_from = count) %>%
  clean_names()

# Property data.

property_tidy <- property_values %>%
  rename("zip" = "zipcode") %>%
  group_by(zip) %>%
  summarize(median_tax = median(gross_tax), .groups = "drop")

grouped <- field_tidy %>%
  left_join(property_tidy, by = c("zip")) %>%
  filter(zip != "00000")

grouped <- grouped %>%
  left_join(pop, by = c("zip" = "zip_code")) %>%
  mutate(total_by_pop = ((total * 100) / population))

```


```{r csv outputs}

write.csv(pop, file = "outputs/population_zip_ma.csv")

write.csv(grouped, file = "outputs/property_encounters.csv")

```


```{r experimental graphics}
long_grouped <- grouped %>%
  pivot_longer(cols = 3:6, names_to = "basis", values_to = "count")
```


```{r experimental graphics 2}
total <- ggplot(grouped, aes(x = median_tax, y = total, size = population)) + 
  geom_point() + 
  theme_classic() + 
  labs(
    title = "Total Police Interactions by Median Property Tax Rate",
    subtitle = "Observations distinguished by zip code",
    x = "Median Property Tax Rate",
    y = "Total Police Interactions",
    size = "Population"
  )

ggsave(filename = "visualizations/total_encounters.png", plot = total)


total_basis <- long_grouped %>%
  group_by(basis) %>%
  filter(!is.na(count)) %>%
  summarize(n = sum(count), .groups = "drop") %>%
  arrange(desc(n)) %>%
  ggplot(aes(x = basis, y = n)) + geom_col(width = .75) + labs(
    title = "Total Encounters By Basis",
    x = "Basis",
    y = "Number of Encounters"
  ) +
  theme_classic()

ggsave(filename = "visualizations/total_encounters_basis.png", plot = total_basis)

total

```


```{r experimental graphics 3}

library(gganimate)
library(gifski)

p <- ggplot(long_grouped, aes(x = median_tax, y = count, size = population)) + 
  geom_point() +
  theme_classic()

propertytax_encounters <- p + 
  transition_states(basis,
                    transition_length = 2,
                    state_length = 1) + 
   ggtitle("Police Interactions by Basis in Boston Counties") +
  labs(
    x = "Median Property Tax",
    y = "Police Encounters",
    subtitle = "Now showing: {closest_state}"
  )

anim_save(animation = propertytax_encounters, filename = "visualizations/encounters_tax.gif")
```


```{r experimental graphics 4}

encounters_basis <- long_grouped %>%
  ggplot(aes(x = zip, y = count, size = population)) + geom_point() + 
  theme_classic() + 
  transition_states(basis,
                    transition_length = 2,
                    state_length = 1) + 
   ggtitle("Police Interactions by Basis in Boston Counties") + 
  labs(
    x = "County",
    y = "Number of Encounters",
    subtitle = "Now showing: {closest_state}"
  ) + 
  theme(axis.ticks.x=element_blank(),
        axis.text.x=element_blank())

anim_save(animation = encounters_basis, filename = "visualizations/encounters_basis.gif")
```





